parser:
  file-path: /Users/vladimir/AC.MOS/АИС КНД/Справочники/Эталонный_спрапвочник_для_загрузки.xlsx
  # categories
  #output-path: /Users/vladimir/AC.MOS/АИС КНД/Справочники/temp-categories.csv
  #column-for-parse: 2

  # conditions
  #output-path: /Users/vladimir/AC.MOS/АИС КНД/Справочники/temp-conditions.csv
  #column-for-parse: 3

  # quality
  #output-path: /Users/vladimir/AC.MOS/АИС КНД/Справочники/temp-quality.csv
  #column-for-parse: 5

  # Volumes
  output-path: /Users/vladimir/AC.MOS/АИС КНД/Справочники/temp-volumes.csv
  column-for-parse: 6

  sheet-index: 1
  in-delimiter: ;
  out-delimiter: ;